### PR TITLE
Add Japanese documents

### PR DESCRIPTION
**Pull request by fisuda**

### CODE REVIEW

**Comment by taliaga** [comment]
Hi @fisuda thanks for this PR. Please, have a look at my comment at 
https://github.com/smartsdk/smartsdk-recipes/pull/44.
What do you think?

**Comment by fisuda** [comment]
Hi @taliaga,

Sorry for the late reply. I commented at https://github.com/smartsdk/smartsdk-recipes/pull/44. Please see it.

**Comment by fisuda** [comment]
I removed `.js` and `.json` files. The pictures in the documents are not shown if  `.png` files are removed. So, I kept them. Please check PR again.

**Comment by taliaga** [comment]
Excellent! thank you so much!

> pictures in the documents are not shown if `.png` files are removed

To avoid duplicating the size of the repo, did you try with a sym-links to the original `.png` files under `doc/` ?.  Something like,

```
cd docs.ja/platform/images/
ln -s ../../../docs/platform/images/01-create-account-fiware-lab-01.png 01-create-account-fiware-lab-01.png 
```

**Comment by fisuda** [comment]
Please check PR again.

**Comment by taliaga** [comment]
Thank you for your patience!

I won't bother you after all the translation efforts with this because it's not critical, but just for you to know, the lint job is now complaining because some lines went beyond 80 characters and some other minor details. You can check them [here](https://travis-ci.org/smartsdk/guided-tour/jobs/410627388).

Thanks again!

**Review by taliaga — APPROVED** [review]

**Comment by fisuda** [comment]
Thank you for taking your time for my PR. 
I will check the lint messages.

**Pull request merged**
